# the ampersand and name create an alias to an item
# the "<<" is used to merge two hashes together and the asterisk plus a name dereferences an alias
# See http://viewsourcecode.org/why/redhanded/bits/yamlSMergeKey.html

common:
  static: &common_static
    logdriver_class: "net.rkbloom.logdriver.LogDriver"
  server: &common_server
    <<: *common_static
    username: "candlepin"
    password: ""

postgresql: &default
  static: &postgresql_static
    driver_class: "org.postgresql.Driver"
    dialect: "org.hibernate.dialect.PostgreSQL92Dialect"
    quartz_driver: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
  server:
    <<: *common_server
    <<: *postgresql_static
    jdbc_url: "jdbc:postgresql://$DB_HOST/$DB_NAME"

# Buildr's default environment is "development" so
# by default, go against postgresql.
development:
  <<: *default

mysql:
  static: &mysql_static
    driver_class: "org.mariadb.jdbc.Driver"
    dialect: "org.hibernate.dialect.MariaDBDialect"
    quartz_driver: "org.quartz.impl.jdbcjobstore.StdJDBCDelegate"
  server:
    <<: *common_server
    <<: *mysql_static
    jdbc_url: "jdbc:mariadb://$DB_HOST/$DB_NAME"
