## this is just for building the containers, meant to be used with the build-images script
---
version: '3'
services:
  candlepin-base:
    build: candlepin-base/
    image: ${REGISTRY}/candlepin-base
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
